### ISSUE TITLE
Calm down/wake up banner overlapping with Kalm

### ISSUE THREAD

**Issue by TheNoim** [himynameisubik/Kalm-support#233]
General information:
===

**Kalm version:** 3.0.0

**Kalm preferences file:** https://pastebin.com/u2YfjzZz

Device information:
===

**iOS version and language:** 14.2 (Language: English, Region: Germany)

**Device:** iPhone 12 Pro

**Jailbreak:** unc0ver 6.0.0

Bug description:
===

**Describe the bug:**

The calm down and wake up banner is not really compatible with kalm. Both screens overlap with each other. The kalm and sleep mode screen.

![photo_2021-03-01_10-35-09](https://user-images.githubusercontent.com/5133056/109479636-e0243480-7a7a-11eb-9fba-9bed728f62d0.jpg)

**How to reproduce:**

1. Enable sleep schedule in health app
2. Enable Sleep Mode in health app
3. Wait until sleep mode turns on
4. Profit

The same thing happens with the morning wake up screen.

**Expected behavior:**

The screens should not overlap with my calendar events. 

**Screenshots:**

See bug description.

Additional information:
===

**Tweak list:**

https://pastebin.com/8wnfLSYd

**Crashlog:**

No crash log.

**Comment by himynameisubik** [comment]
Thanks for reporting this here, it's already been worked on since this tweet https://twitter.com/ShotSkydiver/status/1365961600893509632

However, it won't be an easy solution as I'm not sure yet, what to do. Depending on your Kalm layout and or use of Up Next it won't have an issue. For now I advise to disable the Slee Mode overlay.

**Comment by himynameisubik** [comment]
Kalm 3.0.1 was released.
https://twitter.com/HiMyNameIsUbik/status/1372534026502873093
