### ISSUE TITLE
Random Black Screen: Information

### ISSUE THREAD

**Issue by himynameisubik** [himynameisubik/Kalm-support#75]
# This post is for gathering information only. For discussion about this issue go to #26 

## Some users mentioned a random black screen issue that would not allow the device to wake up.
- For some users it happens at random times, for some at 00:00
- For some users reinstalling the Calendar and Reminders app fixed the issue
- For some users the issue was fixed in 1.2.2
- For some users the issue was fixed in 1.3.4
- For some users the "Fix random resprings" tweak that disables the memory limit for SpringBoard fixed the issue: [reddit release post](https://www.reddit.com/r/jailbreak/comments/g8fzw0/release_fix_random_freezes_and_resprings_deb/)

Unfortunately at the moment everything is just a guess as _none_ of my 4 devices (iPhone X, iPhone 8, iPhone SE and iPhone 6) have had this issue. I'm really trying to find out, what it could be but I'm pretty much just looking for a needle in a haystack.

## Still have this issue **after** following **all** of the general steps to try from [here](https://github.com/himynameisubik/Kalm-support#general-steps-to-try-before-creating-an-issue) and tried installing the tweak Fix random resprings from [here](https://www.reddit.com/r/jailbreak/comments/g8fzw0/release_fix_random_freezes_and_resprings_deb/)?

Please add the following information to this issue (everything else will be deleted/hidden):
- **Device:**

- **iOS version:**

- **Jailbreak:**

- **Kalm version:**

- **Kalm preferences file:** _Upload it to [www.pastebin.com](https://www.pastebin.com)_
`/var/mobile/Library/Preferences/hi.my.name.is.ubik.kalm.plist`

- **Tweak list:** _Upload it to [www.pastebin.com](https://www.pastebin.com)_

- **Amount of calendars in Kalm > Up Next Settings > Select calendars:**

- **Any additional information on the moment/time the issue is occuring**:

**Comment by jinshah05** [comment]
after 2 days black screen again. No reminder and alarm enabled. No Fix Freeze tweak installed.

Also, inform you about temporary solutions who have this issue. If whenever black screen issue appears, just plugin you cable with pc. it will revoke after couple of minutes.

**Comment by jinshah05** [comment]
Hi. I just install "Fix Random Freezing and respring" tweak, But black screen freezes again after installing this tweak. and what is the kalm version before you update alarm and reminder features? If there is again a random black freezing issue then I will downgrade the version to check out.

**Comment by jinshah05** [comment]
Hi, I just want to say after installing "Fix Random Freezing and respring" tweak and re-jailbroken, the issue is still going on. My phone just freeze on black screen.

**Comment by Mi-Rei** [comment]
**Device:** iPhone 11 Pro Max
**iOS version:** 13.5
**Jailbreak:** unc0ver 5.2.0
**Kalm version:** 1.4.2
**Kalm preferences file:** https://pastebin.com/4buEV6X5
**Tweak list:** https://pastebin.com/JfaeP6GE
**Amount of calendars in Kalm > Up Next Settings > Select calendars:** 5. Currently all enabled (none selected). Tried 1,2,3,4, issue persists.
**Any additional information on the moment/time the issue is occuring:** Always occurring somewhere around 23:45-24:15. Suspected 24:00, any change of day. If the device is unused/locked around that time, it will not wake up and always stuck in the black screen, and phone must be hard-reset and re-jailbreak. If the device is used it will not suddenly crash, BUT as soon as it is locked at any time past 24:00, it will immediately stuck in black screen and no longer wake up.

**Comment by himynameisubik** [comment]
Closing for now as there seems to be no luck in fixing this issue. If there is any news coming up from a crashing users side, I can look into it again. Sorry for any inconvenience.
